name: newtest
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # https://pub.dev/packages/sembast
  sembast: ^3.1.0+2
  path: ^1.8.0
  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.14
  # https://pub.dev/packages/http
  http: ^0.13.3
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  flutter_local_notifications: ^14.1.0
  firebase_core_platform_interface: ^4.5.2
  firebase_messaging: ^14.2.1 
  curved_navigation_bar: ^1.0.1
  dropdownfield: ^1.0.3
  timeline_tile: ^2.0.0
  timeline_list: ^0.0.6
  scrollable_positioned_list: ^0.3.5
  like_button: ^2.0.4
  percent_indicator: ^4.2.2
  syncfusion_flutter_charts: ^20.4.44
  intl: ^0.17.0
  month_year_picker: ^0.2.0+3
  # https://pub.dev/packages/email_validator
  email_validator: ^2.1.17
  # https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # https://pub.dev/packages/provider
  provider: ^6.0.5
  # https://pub.dev/packages/flutter_expanded_tile
  flutter_expanded_tile: ^0.3.7
  # https://pub.dev/packages/pie_chart
  pie_chart: ^5.3.2
  # https://pub.dev/packages/flutter_slidable
  flutter_slidable: ^3.0.0
  # https://pub.dev/packages/dialog_flowtter
  dialog_flowtter: ^0.3.3
  # https://pub.dev/packages/dio
  dio: ^5.1.2
  shared_preferences: ^2.1.2
  badges: ^3.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - asset/image/
    - asset/dialog_flow/dialog_flow.json

  uses-material-design: true

